#!/usr/bin/env bash

set -e


gcloud compute networks create privatenet --subnet-mode=custom

gcloud compute networks subnets create privatesubnet-us --network=privatenet --region=us-central1 --range=172.16.0.0/24

gcloud compute networks subnets create privatesubnet-eu --network=privatenet --region=europe-west4 --range=172.20.0.0/20


gcloud compute networks create managementnet --subnet-mode=custom

gcloud compute networks subnets create managementnetsubnet-us --network=managementnet --region=us-central1 --range=10.130.0.0/20


gcloud compute firewall-rules create privatenet-allow-icmp-ssh-rdp --direction=INGRESS --priority=1000 --network=privatenet --action=ALLOW --rules=icmp,tcp:22,tcp:3389 --source-ranges=0.0.0.0/0

gcloud compute firewall-rules create managementnet-allow-icmp-ssh-rdp --direction=INGRESS --priority=1000 --network=managementnet --action=ALLOW --rules=icmp,tcp:22,tcp:3389 --source-ranges=0.0.0.0/0

echo -e " creating a vm in us-central1-f zone \n " 

gcloud compute instances create managementnet-us-vm \
    --network=managementnet \
    --subnet=managementnetsubnet-us \
    --zone=us-central1-f \
     --machine-type=f1-micro

gcloud compute instances create privatenet-us-vm --zone=us-central1-f --machine-type=n1-standard-1 --subnet=privatesubnet-us

echo -e " now head towards \n Create the VM instance with multiple network interfaces " 
